---

name: Aiohttp


on:
  merge_group:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master


env:
  COLOR: "yes"
  FORCE_COLOR: 1
  PY_COLORS: 1


jobs:

  test-aiohttp:
    name: Aiohttp tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        branch: ['master', '3.12', '3.13']
    steps:
    - name: Checkout aiohttp
      uses: actions/checkout@v5
      with:
        repository: aio-libs/aiohttp
        ref: ${{ matrix.branch }}
        submodules: true
    - name: Checkout yarl
      uses: actions/checkout@v5
      with:
        path: vendor/yarl
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: requirements/*.txt
    - name: Provision the dev env
      run: make .develop
    - name: Cythonize yarl
      working-directory: vendor/yarl
      run: make cythonize
    - name: Install yarl
      working-directory: vendor/yarl
      run: >-
        python -m pip install -e .
    - name: Run tests
      run: python -m pytest
      shell: bash

...
